name: Deploy Lambda
description: Action for deploying to AWS Lambda


jobs:
  # add rules so this only runs on specific branches
  deploy:
    name: Deploy ${{environment}}
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Outputs
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: List files in the repository
        run: ls ${{ github.workspace }}         