#----------------------------------------------------------------------------------------------------------------------
# This workflow will execute to build and test the application on commits to development branches
#----------------------------------------------------------------------------------------------------------------------
name: Development Pipeline

on: 
  push:
    branches-ignore:
      - 'main'
      - 'alpha'
      - 'beta'
      - 'qa'

jobs:

  build-test:
     uses: ./.github/workflows/buildandtest.yml      