#----------------------------------------------------------------------------------------------------------------------
# This workflow should only execute when code is committed to main which means it has passed QA testing and should
# be ready to go to UAT and Production
#----------------------------------------------------------------------------------------------------------------------
name: Main Pipeline

on: 
  push:
    branches:
      - 'main'

jobs:

  build:
     uses: ./.github/workflows/build.yml

  deploy-qa: 
    name: Deploy QA
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qa
    needs: [ build ]

  deploy-uat: 
    name: Deploy UAT
    uses: ./.github/workflows/deploy.yml
    with:
      environment: uat
    needs: [ deploy-uat ]

  deploy-prod: 
    name: Deploy PROD
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    needs: [ deploy-uat ]